package _27089.Q9;

import java.time.LocalDate;
import java.util.Scanner;
import java.util.function.Consumer;
import java.util.function.DoubleConsumer;
import java.util.function.IntConsumer;

public class Main {
    private static final Scanner sc = new Scanner(System.in);

    public static void main(String[] args) {
        System.out.println("===========================================");
        System.out.println("   AIRLINE TICKETING SYSTEM (ID: 27089)");
        System.out.println("===========================================");

        TicketRecord record = new TicketRecord();

        record.setId(901);
        record.setCreatedDate(LocalDate.now());

        System.out.println("--- AIRLINE INFO ---");
        getString("Airline Name:   ", record::setAirlineName);
        getString("Address:        ", record::setAddress);
        getString("Contact Email:  ", record::setContactEmail);

        System.out.println("\n--- FLIGHT DETAILS ---");
        getString("Flight Number:  ", record::setFlightNumber);
        getString("Destination:    ", record::setDestination);
        getString("Departure Time: ", record::setDepartureTime);

        System.out.println("\n--- PASSENGER INFO ---");
        getString("Passenger Name: ", record::setPassengerName);
        getString("Passport No:    ", record::setPassportNumber);
        getString("Nationality:    ", record::setNationality);

        System.out.println("\n--- SEAT SELECTION ---");
        getString("Seat Number:    ", record::setSeatNumber);
        // This will trigger the Economy/Business check loop
        getString("Type (Eco/Bus): ", record::setSeatType);

        System.out.println("\n--- TICKET & BAGGAGE ---");
        getString("Ticket Number:  ", record::setTicketNumber);
        getDouble("Ticket Price:   ", record::setPrice);
        getDouble("Baggage Wt(kg): ", record::setBaggageWeight);
        getDouble("Baggage Fee:    ", record::setBaggageFee);

        System.out.println("\n--- PAYMENT ---");
        getString("Payment Date:   ", record::setPaymentDate);
        getString("Payment Mode:   ", record::setPaymentMode);

        // FINAL OUTPUT
        System.out.println("\n===========================================");
        System.out.println("         FINAL TICKET RECORD");
        System.out.println("===========================================");
        System.out.println("AIRLINE:    " + record.getAirlineName() + " [" + record.getContactEmail() + "]");
        System.out.println("FLIGHT:     " + record.getFlightNumber() + " to " + record.getDestination() + " @ " + record.getDepartureTime());
        System.out.println("-------------------------------------------");
        System.out.println("PASSENGER:  " + record.getPassengerName());
        System.out.println("PASSPORT:   " + record.getPassportNumber() + " (" + record.getNationality() + ")");
        System.out.println("SEAT:       " + record.getSeatNumber() + " [" + record.getSeatType().toUpperCase() + "]");
        System.out.println("-------------------------------------------");
        System.out.printf("BASE PRICE:  FRW %.2f\n", record.getPrice());
        System.out.printf("BAGGAGE FEE: FRW %.2f (%.1f kg)\n", record.getBaggageFee(), record.getBaggageWeight());
        System.out.printf("TOTAL FARE:  FRW %.2f\n", record.generateInvoice());
        System.out.println("-------------------------------------------");
        System.out.println("PAID VIA:    " + record.getPaymentMode() + " on " + record.getPaymentDate());
        System.out.println("===========================================");
        System.out.println("Generated by ID: 27089");

        sc.close();
    }

    // --- HELPER METHODS ---

    private static void getString(String prompt, Consumer<String> setter) {
        while (true) {
            System.out.print(prompt);
            String input = sc.nextLine();
            try {
                setter.accept(input);
                break;
            } catch (RuntimeException e) {
                System.err.println("  [Error]: " + e.getMessage() + ". Try again.");
            }
        }
    }

    private static void getDouble(String prompt, DoubleConsumer setter) {
        while (true) {
            System.out.print(prompt);
            try {
                double val = Double.parseDouble(sc.nextLine());
                setter.accept(val);
                break;
            } catch (NumberFormatException e) {
                System.err.println("  [Error]: Invalid decimal. Try again.");
            } catch (RuntimeException e) {
                System.err.println("  [Error]: " + e.getMessage() + ". Try again.");
            }
        }
    }

    // getInt included just in case you add ID fields later
    private static void getInt(String prompt, IntConsumer setter) {
        while (true) {
            System.out.print(prompt);
            try {
                int val = Integer.parseInt(sc.nextLine());
                setter.accept(val);
                break;
            } catch (NumberFormatException e) {
                System.err.println("  [Error]: Invalid number. Try again.");
            } catch (RuntimeException e) {
                System.err.println("  [Error]: " + e.getMessage() + ". Try again.");
            }
        }
    }
}