package _27089.Q7;

import java.time.LocalDate;
import java.util.Scanner;
import java.util.function.Consumer;
import java.util.function.DoubleConsumer;


public class Main {
    private static final Scanner sc = new Scanner(System.in);

    public static void main(String[] args) {
        System.out.println("===========================================");
        System.out.println("  REAL ESTATE MANAGEMENT SYSTEM (ID: 27089)");
        System.out.println("===========================================");

        RealEstateRecord record = new RealEstateRecord();

        record.setId(701);
        record.setCreatedDate(LocalDate.now());

        System.out.println("--- AGENCY INFO ---");
        getString("Agency Name:   ", record::setAgencyName);
        getString("Location:      ", record::setLocation);
        getString("Agency Phone:  ", record::setPhoneNumber);

        System.out.println("\n--- AGENT DETAILS ---");
        getString("Agent Name:    ", record::setAgentName);
        getString("Agent Email:   ", record::setEmail);
        getString("License No:    ", record::setLicenseNumber);

        System.out.println("\n--- PROPERTY DETAILS ---");
        getString("Property Code: ", record::setPropertyCode);
        getString("Type:          ", record::setPropertyType);
        getDouble("Price (FRW):   ", record::setPrice);

        System.out.println("\n--- PARTIES ---");
        getString("Seller Name:   ", record::setSellerName);
        getString("Seller Phone:  ", record::setContactNumber);

        getString("Buyer Name:    ", record::setBuyerName);
        getString("Buyer Email:   ", record::setBuyerEmail);

        System.out.println("\n--- AGREEMENT & PAYMENT ---");
        getString("Agree Date:    ", record::setAgreementDate);
        getString("Terms:         ", record::setTerms);

        getDouble("Payment Amt:   ", record::setPaymentAmount);
        getString("Payment Date:  ", record::setPaymentDate);

        System.out.println("\n--- COMMISSION ---");
        getDouble("Comm Rate (%): ", record::setCommissionRate);

        // FINAL OUTPUT
        System.out.println("\n===========================================");
        System.out.println("         FINAL REAL ESTATE RECORD");
        System.out.println("===========================================");
        System.out.println("AGENCY:     " + record.getAgencyName() + " (" + record.getPhoneNumber() + ")");
        System.out.println("AGENT:      " + record.getAgentName() + " | Lic: " + record.getLicenseNumber());
        System.out.println("-------------------------------------------");
        System.out.println("PROPERTY:   " + record.getPropertyType() + " [" + record.getPropertyCode() + "]");
        System.out.println("PRICE:      FRW " + record.getPrice());
        System.out.println("-------------------------------------------");
        System.out.println("SELLER:     " + record.getSellerName());
        System.out.println("BUYER:      " + record.getBuyerName());
        System.out.println("AGREEMENT:  " + record.getAgreementDate());
        System.out.println("-------------------------------------------");
        // Calculation Display
        System.out.printf("COMMISSION: FRW %.2f (at %.1f%% rate)\n",
                record.calculateCommission(), record.getCommissionRate());

        System.out.printf("TOTAL WITH COMMISSION: FRW %.2f \n",
                record.calculateCommission()+ record.getPrice());
        System.out.println("===========================================");
        System.out.println("Generated by ID: 27089");

        sc.close();
    }



    private static void getString(String prompt, Consumer<String> setter) {
        while (true) {
            System.out.print(prompt);
            String input = sc.nextLine();
            try {
                setter.accept(input);
                break;
            } catch (RuntimeException e) {
                System.err.println("  [Error]: " + e.getMessage() + ". Try again.");
            }
        }
    }

    private static void getDouble(String prompt, DoubleConsumer setter) {
        while (true) {
            System.out.print(prompt);
            try {
                double val = Double.parseDouble(sc.nextLine());
                setter.accept(val);
                break;
            } catch (NumberFormatException e) {
                System.err.println("  [Error]: Invalid decimal. Try again.");
            } catch (RuntimeException e) {
                System.err.println("  [Error]: " + e.getMessage() + ". Try again.");
            }
        }
    }

}