package _27089.Q5;

import java.time.LocalDate;
import java.util.Scanner;
import java.util.function.Consumer;
import java.util.function.DoubleConsumer;
import java.util.function.IntConsumer;

public class Main {
    private static final Scanner sc = new Scanner(System.in);

    public static void main(String[] args) {
        System.out.println("===========================================");
        System.out.println("   VEHICLE RENTAL SYSTEM (ID: 27089)");
        System.out.println("===========================================");

        RentalRecord record = new RentalRecord();

        record.setId(501);
        record.setCreatedDate(LocalDate.now());

        System.out.println("--- COMPANY DETAILS ---");
        getString("Company Name:  ", record::setCompanyName);
        getString("Address:       ", record::setAddress);
        getString("Phone:         ", record::setPhoneNumber);

        System.out.println("\n--- BRANCH INFO ---");
        getString("Branch Name:   ", record::setBranchName);
        getString("Location Code: ", record::setLocationCode);

        System.out.println("\n--- VEHICLE INFO ---");
        getString("Vehicle Type:  ", record::setVehicleType);
        getString("Reg Number:    ", record::setRegistrationNumber);
        getDouble("Daily Rate:    ", record::setDailyRate);

        System.out.println("\n--- CUSTOMER INFO ---");
        getString("Customer Name: ", record::setCustomerName);
        getString("License No:    ", record::setLicenseNumber);
        getString("Contact No:    ", record::setContactNumber);

        System.out.println("\n--- RENTAL DETAILS ---");
        getString("Rental Date:   ", record::setRentalDate);
        getString("Return Date:   ", record::setReturnDate);
        getInt("Rental Days:   ", record::setRentalDays);

        System.out.println("\n--- CHARGES ---");
        getDouble("Rental Charge: ", record::setRentalCharge);
        getDouble("Penalty Charge:", record::setPenaltyCharge);

        System.out.println("\n--- PAYMENT & INVOICE ---");
        getString("Payment Mode:  ", record::setPaymentMode);
        getString("Transaction ID:", record::setTransactionId);



        System.out.println("\n===========================================");
        System.out.println("         FINAL RENTAL RECORD");
        System.out.println("===========================================");
        System.out.println("COMPANY:    " + record.getCompanyName() + " (" + record.getBranchName() + ")");
        System.out.println("VEHICLE:    " + record.getVehicleType() + " [" + record.getRegistrationNumber() + "]");
        System.out.println("CUSTOMER:   " + record.getCustomerName() + " | Lic: " + record.getLicenseNumber());
        System.out.println("-------------------------------------------");
        System.out.println("PERIOD:     " + record.getRentalDays() + " days (" + record.getRentalDate() + " to " + record.getReturnDate() + ")");
        System.out.println("RATE:        " + record.getDailyRate() + " as rating. Thanks for your feedback! 🎉");
        System.out.println("-------------------------------------------");
        System.out.printf("RENTAL CHG:  FRW %.2f\n", record.getRentalCharge());
        System.out.printf("PENALTY:     FRW %.2f\n", record.getPenaltyCharge());
        System.out.printf("TOTAL:       FRW %.2f\n", record.calculateTotalCharge());
        System.out.println("-------------------------------------------");
        System.out.println("PAYMENT:    " + record.getPaymentMode() + " (TXN: " + record.getTransactionId() + ")");
        System.out.println("===========================================");
        System.out.println("Generated by ID: 27089");

        sc.close();
    }

    // --- HELPER METHODS ---

    private static void getString(String prompt, Consumer<String> setter) {
        while (true) {
            System.out.print(prompt);
            String input = sc.nextLine();
            try {
                setter.accept(input);
                break;
            } catch (RuntimeException e) {
                System.err.println("  [Error]: " + e.getMessage() + ". Try again.");
            }
        }
    }

    private static void getInt(String prompt, IntConsumer setter) {
        while (true) {
            System.out.print(prompt);
            try {
                int val = Integer.parseInt(sc.nextLine());
                setter.accept(val);
                break;
            } catch (NumberFormatException e) {
                System.err.println("  [Error]: Invalid number. Try again.");
            } catch (RuntimeException e) {
                System.err.println("  [Error]: " + e.getMessage() + ". Try again.");
            }
        }
    }

    private static void getDouble(String prompt, DoubleConsumer setter) {
        while (true) {
            System.out.print(prompt);
            try {
                double val = Double.parseDouble(sc.nextLine());
                setter.accept(val);
                break;
            } catch (NumberFormatException e) {
                System.err.println("  [Error]: Invalid decimal. Try again.");
            } catch (RuntimeException e) {
                System.err.println("  [Error]: " + e.getMessage() + ". Try again.");
            }
        }
    }
}