package _27089.Q3;

import java.time.LocalDate;
import java.util.Scanner;
import java.util.function.Consumer;
import java.util.function.DoubleConsumer;
import java.util.function.IntConsumer;

public class Main {
    // Global Scanner so helper methods can see it
    private static final Scanner sc = new Scanner(System.in);

    public static void main(String[] args) {

        System.out.println("===========================================");
        System.out.println("    EMPLOYEE PAYROLL SYSTEM (ID: 27089)");
        System.out.println("===========================================");

        // We don't need a big try-catch around the whole thing anymore!
        // because the helper methods handle errors individually.

        PayrollRecord record = new PayrollRecord();

        // 1. Company (Auto-set)
        record.setId(301);
        record.setCreatedDate(LocalDate.now());

        System.out.println("--- COMPANY INFO ---");
        // Usage: getString(Prompt, Setter Method)
        getString("Company Name: ", record::setCompanyName);
        getString("Address:      ", record::setAddress);
        getString("Phone:        ", record::setPhoneNumber);
        getString("Email:        ", record::setEmail);

        // 2. Department & Manager
        System.out.println("\n--- DEPT & MANAGER ---");
        getString("Dept Name:    ", record::setDepartmentName);
        getString("Dept Code:    ", record::setDepartmentCode);

        getString("Manager Name: ", record::setManagerName);
        getString("Manager Email:", record::setManagerEmail);
        getString("Manager Phone:", record::setPhone);

        // 3. Employee
        System.out.println("\n--- EMPLOYEE DETAILS ---");
        getString("Employee Name:", record::setEmployeeName);
        getString("Designation:  ", record::setDesignation);
        getString("Contact No:   ", record::setContactNumber);
        getInt("Employee ID:  ", record::setEmployeeId);

        // 4. Attendance
        System.out.println("\n--- ATTENDANCE ---");
        getInt("Total Days:   ", record::setTotalDays);
        getInt("Days Present: ", record::setPresentDays);
        getInt("Days Leave:   ", record::setLeaveDays);

        // 5. Financials
        System.out.println("\n--- FINANCIALS ---");
        getDouble("Basic Salary:       ", record::setBasicSalary);
        getDouble("Housing Allowance:  ", record::setHousingAllowance);
        getDouble("Transport Allowance:", record::setTransportAllowance);
        getDouble("Tax Deduction:      ", record::setTaxDeduction);
        getDouble("Loan Deduction:     ", record::setLoanDeduction);

        // Output
        System.out.println("\n===========================================");
        System.out.println("         FINAL PAYROLL RECORD");
        System.out.println("===========================================");
        System.out.println("COMPANY:    " + record.getCompanyName());
        System.out.println("DEPT:       " + record.getDepartmentName() + " (Mgr: " + record.getManagerName() + ")");
        System.out.println("-------------------------------------------");
        System.out.println("EMPLOYEE:   " + record.getEmployeeName() + " [ID: " + record.getEmployeeId() + "]");
        System.out.println("ATTENDANCE: " + record.getPresentDays() + "/" + record.getTotalDays() + " Days Present");
        System.out.println("-------------------------------------------");
        System.out.printf("BASIC SALARY:   FRW %.2f\n", record.getBasicSalary());
        System.out.printf("GROSS SALARY:   FRW %.2f\n", record.getGrossSalary());
        System.out.printf("NET SALARY:     FRW %.2f\n", record.calculateNetSalary());
        System.out.println("-------------------------------------------");
        System.out.println("Generated by ID: 27089");
        System.out.println("===========================================");

        sc.close();
    }

    // =============================================================
    // 👇 HELPER METHODS (The Magic "Retry" Logic)
    // =============================================================

    // 1. Helper for String Inputs
    private static void getString(String prompt, Consumer<String> setter) {
        while (true) {
            System.out.print(prompt);
            String input = sc.nextLine();
            try {
                // Try to set the value. If it fails, the Exception is thrown.
                setter.accept(input);
                break; // Success! Exit the loop.
            } catch (RuntimeException e) {
                System.err.println("  [Error]: " + e.getMessage() + ". Try again.");
            }
        }
    }

    // 2. Helper for Integer Inputs
    private static void getInt(String prompt, IntConsumer setter) {
        while (true) {
            System.out.print(prompt);
            try {
                // We use parse so we don't have to deal with buffer clearing!
                int val = Integer.parseInt(sc.nextLine());
                setter.accept(val);
                break;
            } catch (NumberFormatException e) {
                System.err.println("  [Error]: Invalid number. Try again.");
            } catch (RuntimeException e) {
                System.err.println("  [Error]: " + e.getMessage() + ". Try again.");
            }
        }
    }

    // 3. Helper for Double Inputs
    private static void getDouble(String prompt, DoubleConsumer setter) {
        while (true) {
            System.out.print(prompt);
            try {
                double val = Double.parseDouble(sc.nextLine());
                setter.accept(val);
                break;
            } catch (NumberFormatException e) {
                System.err.println("  [Error]: Invalid decimal number. Try again.");
            } catch (RuntimeException e) {
                System.err.println("  [Error]: " + e.getMessage() + ". Try again.");
            }
        }
    }
}