package _27089.Q4;

import java.time.LocalDate;
import java.util.Scanner;
import java.util.function.Consumer;
import java.util.function.DoubleConsumer;
import java.util.function.IntConsumer;

public class Main {
    private static final Scanner sc = new Scanner(System.in);

    public static void main(String[] args) {
        System.out.println("===========================================");
        System.out.println("   HOTEL RESERVATION SYSTEM (ID: 27089)");
        System.out.println("===========================================");

        ReservationRecord record = new ReservationRecord();

        record.setId(401);
        record.setCreatedDate(LocalDate.now());

        System.out.println("--- HOTEL DETAILS ---");
        getString("Hotel Name:  ", record::setHotelName);
        getString("Address:     ", record::setAddress);
        getString("Phone:       ", record::setPhoneNumber);
        getString("Email:       ", record::setEmail);

        System.out.println("\n--- ROOM INFO ---");
        getString("Room Number: ", record::setRoomNumber);
        getString("Room Type:   ", record::setRoomType);
        getDouble("Price/Night: ", record::setPricePerNight);

        System.out.println("\n--- CUSTOMER INFO ---");
        getString("Name:        ", record::setCustomerName);
        getString("Email:       ", record::setCustomerEmail);
        getString("Contact:     ", record::setContactNumber);

        System.out.println("\n--- BOOKING DETAILS ---");
        getString("Booking Date:", record::setBookingDate);
        getString("Check-In:    ", record::setCheckInDate);
        getString("Check-Out:   ", record::setCheckOutDate);

        System.out.println("\n--- SERVICE ---");
        getString("Service Name:", record::setServiceName);
        getDouble("Service Cost:", record::setServiceCost);

        System.out.println("\n--- BILLING ---");
        getDouble("Room Charge:    ", record::setRoomCharge);
        getDouble("Service Charge: ", record::setServiceCharge);
        getString("Payment Method: ", record::setPaymentMethod);
        getString("Payment Date:   ", record::setPaymentDate);

        System.out.println("\n--- FEEDBACK ---");
        getInt("Rating (1-5):   ", record::setRating);
        getString("Comments:       ", record::setComments);

        // Output
        System.out.println("\n===========================================");
        System.out.println("         FINAL RESERVATION RECORD");
        System.out.println("===========================================");
        System.out.println("HOTEL:      " + record.getHotelName());
        System.out.println("CUSTOMER:   " + record.getCustomerName() + " | Room: " + record.getRoomNumber());
        System.out.println("DATES:      " + record.getCheckInDate() + " to " + record.getCheckOutDate());
        System.out.println("SERVICE:    " + record.getServiceName());
        System.out.println("-------------------------------------------");
        System.out.printf("ROOM CHARGE:    FRW %.2f\n", record.getRoomCharge());
        System.out.printf("SERVICE CHARGE: FRW %.2f\n", record.getServiceCharge());
        System.out.printf("TOTAL BILL:     FRW %.2f\n", record.generateBill());
        System.out.println("-------------------------------------------");
        System.out.println("RATING:     " + record.getRating() + "/5");
        System.out.println("COMMENTS:   " + record.getComments());
        System.out.println("===========================================");
        System.out.println("Generated by ID: 27089");

        sc.close();
    }



    private static void getString(String prompt, Consumer<String> setter) {
        while (true) {
            System.out.print(prompt);
            String input = sc.nextLine();
            try {
                setter.accept(input);
                break;
            } catch (RuntimeException e) {
                System.err.println("  [Error]: " + e.getMessage() + ". Try again.");
            }
        }
    }

    private static void getInt(String prompt, IntConsumer setter) {
        while (true) {
            System.out.print(prompt);
            try {
                int val = Integer.parseInt(sc.nextLine());
                setter.accept(val);
                break;
            } catch (NumberFormatException e) {
                System.err.println("  [Error]: Invalid number. Try again.");
            } catch (RuntimeException e) {
                System.err.println("  [Error]: " + e.getMessage() + ". Try again.");
            }
        }
    }

    private static void getDouble(String prompt, DoubleConsumer setter) {
        while (true) {
            System.out.print(prompt);
            try {
                double val = Double.parseDouble(sc.nextLine());
                setter.accept(val);
                break;
            } catch (NumberFormatException e) {
                System.err.println("  [Error]: Invalid decimal. Try again.");
            } catch (RuntimeException e) {
                System.err.println("  [Error]: " + e.getMessage() + ". Try again.");
            }
        }
    }
}