package _27089.Q10;

import java.time.LocalDate;
import java.util.Scanner;
import java.util.function.Consumer;
import java.util.function.DoubleConsumer;
import java.util.function.IntConsumer;

public class Main {
    private static final Scanner sc = new Scanner(System.in);

    public static void main(String[] args) {
        System.out.println("===========================================");
        System.out.println("    ONLINE SHOPPING SYSTEM (ID: 27089)");
        System.out.println("===========================================");

        OrderRecord record = new OrderRecord();

        record.setId(1001);
        record.setCreatedDate(LocalDate.now());

        System.out.println("--- STORE DETAILS ---");
        getString("Store Name:    ", record::setStoreName);
        getString("Store Address: ", record::setAddress);
        getString("Store Email:   ", record::setEmail);

        System.out.println("\n--- CATEGORY ---");
        getString("Cat Name:      ", record::setCategoryName);
        getString("Cat Code:      ", record::setCategoryCode);

        System.out.println("\n--- PRODUCT ---");
        getString("Prod Name:     ", record::setProductName);
        getString("Prod Code:     ", record::setProductCode);
        getDouble("Price (FRW):   ", record::setPrice);

        System.out.println("\n--- CUSTOMER INFO ---");
        getString("Customer Name: ", record::setCustomerName);
        getString("Contact No:    ", record::setContactNumber);
        getString("Cust Address:  ", record::setCustomerAddress);

        System.out.println("\n--- ORDER INFO ---");
        getString("Order ID:      ", record::setOrderId);
        getString("Order Date:    ", record::setOrderDate);

        System.out.println("\n--- PAYMENT ---");
        getString("Pay Method:    ", record::setPaymentMethod);
        getString("Pay Status:    ", record::setPaymentStatus);

        System.out.println("\n--- SHIPPING ---");
        getString("Ship Address:  ", record::setShippingAddress);
        getDouble("Ship Cost:     ", record::setShippingCost);

        // FINAL OUTPUT
        System.out.println("\n===========================================");
        System.out.println("         FINAL ORDER RECORD");
        System.out.println("===========================================");
        System.out.println("STORE:      " + record.getStoreName() + " (" + record.getEmail() + ")");
        System.out.println("PRODUCT:    " + record.getProductName() + " [" + record.getCategoryName() + "]");
        System.out.println("-------------------------------------------");
        System.out.println("CUSTOMER:   " + record.getCustomerName());
        System.out.println("ORDER ID:   " + record.getOrderId() + " on " + record.getOrderDate());
        System.out.println("SHIPPING:   To " + record.getShippingAddress());
        System.out.println("-------------------------------------------");
        System.out.printf("ITEM PRICE:  FRW %.2f\n", record.getPrice());
        System.out.printf("SHIP COST:   FRW %.2f\n", record.getShippingCost());
        System.out.printf("TOTAL:       FRW %.2f\n", record.calculateTotalAmount());
        System.out.println("-------------------------------------------");
        System.out.println("PAYMENT:    " + record.getPaymentMethod() + " (" + record.getPaymentStatus() + ")");
        System.out.println("===========================================");
        System.out.println("Generated by ID: 27089");

        sc.close();
    }

    // --- HELPER METHODS ---

    private static void getString(String prompt, Consumer<String> setter) {
        while (true) {
            System.out.print(prompt);
            String input = sc.nextLine();
            try {
                setter.accept(input);
                break;
            } catch (RuntimeException e) {
                System.err.println("  [Error]: " + e.getMessage() + ". Try again.");
            }
        }
    }

    private static void getDouble(String prompt, DoubleConsumer setter) {
        while (true) {
            System.out.print(prompt);
            try {
                double val = Double.parseDouble(sc.nextLine());
                setter.accept(val);
                break;
            } catch (NumberFormatException e) {
                System.err.println("  [Error]: Invalid decimal. Try again.");
            } catch (RuntimeException e) {
                System.err.println("  [Error]: " + e.getMessage() + ". Try again.");
            }
        }
    }

    // Included for completeness if ID fields are added later
    private static void getInt(String prompt, IntConsumer setter) {
        while (true) {
            System.out.print(prompt);
            try {
                int val = Integer.parseInt(sc.nextLine());
                setter.accept(val);
                break;
            } catch (NumberFormatException e) {
                System.err.println("  [Error]: Invalid number. Try again.");
            } catch (RuntimeException e) {
                System.err.println("  [Error]: " + e.getMessage() + ". Try again.");
            }
        }
    }
}