package _27089.Q6;

import java.time.LocalDate;
import java.util.Scanner;
import java.util.function.Consumer;
import java.util.function.DoubleConsumer;
import java.util.function.IntConsumer;

public class Main {
    private static final Scanner sc = new Scanner(System.in);

    public static void main(String[] args) {
        System.out.println("===========================================");
        System.out.println("      BANKING SYSTEM (ID: 27089)");
        System.out.println("===========================================");

        AccountRecord record = new AccountRecord();

        record.setId(601);
        record.setCreatedDate(LocalDate.now());

        System.out.println("--- BANK DETAILS ---");
        getString("Bank Name:    ", record::setBankName);
        getString("Branch Code:  ", record::setBranchCode);
        getString("Address:      ", record::setAddress);

        System.out.println("\n--- ACCOUNT DETAILS ---");
        getString("Account No:   ", record::setAccountNumber);
        getString("Account Type: ", record::setAccountType);
        getDouble("Current Bal:  ", record::setBalance);

        System.out.println("\n--- CUSTOMER DETAILS ---");
        getString("Customer Name:", record::setCustomerName);
        getString("Email:        ", record::setEmail);
        getString("Phone No:     ", record::setPhoneNumber);

        System.out.println("\n--- TRANSACTION ---");
        getString("Trans ID:     ", record::setTransactionId);
        getString("Trans Type:   ", record::setTransactionType);
        getDouble("Amount:       ", record::setAmount);

        System.out.println("\n--- ACTIVITY ---");
        getDouble("Deposit Amt:  ", record::setDepositAmount);
        getString("Deposit Date: ", record::setDepositDate);

        getDouble("Withdrawal Amt:", record::setWithdrawalAmount);
        getString("Withdraw Date: ", record::setWithdrawalDate);

        System.out.println("\n--- LOAN DETAILS ---");
        getDouble("Loan Amount:  ", record::setLoanAmount);
        getDouble("Interest Rate:", record::setInterestRate);
        getInt("Duration (Yr):", record::setDuration);

        System.out.println("\n--- LOAN PAYMENT ---");
        getDouble("Payment Amt:  ", record::setPaymentAmount);
        getString("Payment Date: ", record::setPaymentDate);

        // FINAL OUTPUT
        System.out.println("\n===========================================");
        System.out.println("         FINAL ACCOUNT RECORD");
        System.out.println("===========================================");
        System.out.println("BANK:       " + record.getBankName() + " (" + record.getBranchCode() + ")");
        System.out.println("CUSTOMER:   " + record.getCustomerName() + " | Acc: " + record.getAccountNumber());
        System.out.println("BALANCE:    FRW " + record.getBalance());
        System.out.println("-------------------------------------------");
        System.out.println("LOAN INFO:  FRW " + record.getLoanAmount() + " at " + record.getInterestRate() + "% as interest, for " + record.getDuration() + " years");
        System.out.printf("PAYMENT WITH INTEREST INCLUDED:   FRW %.2f\n", record.calculateInterest());
        System.out.println("-------------------------------------------");
        System.out.println("RECENT TXN: " + record.getTransactionType() + " (" + record.getTransactionId() + ")");
        System.out.println("PAYMENT:    FRW " + record.getPaymentAmount() + " on " + record.getPaymentDate());
        System.out.println("===========================================");
        System.out.println("Generated by ID: 27089");

        sc.close();
    }



    private static void getString(String prompt, Consumer<String> setter) {
        while (true) {
            System.out.print(prompt);
            String input = sc.nextLine();
            try {
                setter.accept(input);
                break;
            } catch (RuntimeException e) {
                System.err.println("  [Error]: " + e.getMessage() + ". Try again.");
            }
        }
    }

    private static void getInt(String prompt, IntConsumer setter) {
        while (true) {
            System.out.print(prompt);
            try {
                int val = Integer.parseInt(sc.nextLine());
                setter.accept(val);
                break;
            } catch (NumberFormatException e) {
                System.err.println("  [Error]: Invalid number. Try again.");
            } catch (RuntimeException e) {
                System.err.println("  [Error]: " + e.getMessage() + ". Try again.");
            }
        }
    }

    private static void getDouble(String prompt, DoubleConsumer setter) {
        while (true) {
            System.out.print(prompt);
            try {
                double val = Double.parseDouble(sc.nextLine());
                setter.accept(val);
                break;
            } catch (NumberFormatException e) {
                System.err.println("  [Error]: Invalid decimal. Try again.");
            } catch (RuntimeException e) {
                System.err.println("  [Error]: " + e.getMessage() + ". Try again.");
            }
        }
    }
}