package _27089.Q8;

import java.time.LocalDate;
import java.util.Scanner;
import java.util.function.Consumer;
import java.util.function.DoubleConsumer;
import java.util.function.IntConsumer;

public class Main {
    private static final Scanner sc = new Scanner(System.in);

    public static void main(String[] args) {
        System.out.println("===========================================");
        System.out.println("   LIBRARY MANAGEMENT SYSTEM (ID: 27089)");
        System.out.println("===========================================");

        LibraryRecord record = new LibraryRecord();

        record.setId(801);
        record.setCreatedDate(LocalDate.now());

        System.out.println("--- LIBRARY INFO ---");
        getString("Library Name: ", record::setLibraryName);
        getString("Location:     ", record::setLocation);
        getString("Phone:        ", record::setPhoneNumber);

        System.out.println("\n--- SECTION & BOOK ---");
        getString("Section Name: ", record::setSectionName);
        getString("Section Code: ", record::setSectionCode);

        getString("Book Title:   ", record::setTitle);
        getString("Author:       ", record::setAuthor);
        getString("ISBN:         ", record::setISBN);

        System.out.println("\n--- MEMBER INFO ---");
        getString("Member Name:  ", record::setMemberName);
        getInt("Member ID:    ", record::setMemberId);
        getString("Contact No:   ", record::setContactNumber);

        System.out.println("\n--- BORROW DETAILS ---");
        getString("Borrow Date:  ", record::setBorrowDate);
        getString("Return Date:  ", record::setReturnDate);

        System.out.println("\n--- FINES ---");
        getInt("Days Late:    ", record::setDaysLate);
        getDouble("Fine Per Day: ", record::setFineAmount); // Stored in fineAmount for calculation

        System.out.println("\n--- PAYMENT ---");
        getString("Payment Date: ", record::setPaymentDate);
        getString("Payment Mode: ", record::setPaymentMode);

        // FINAL OUTPUT
        System.out.println("\n===========================================");
        System.out.println("         FINAL LIBRARY RECORD");
        System.out.println("===========================================");
        System.out.println("LIBRARY:    " + record.getLibraryName() + " [" + record.getLocation() + "]");
        System.out.println("BOOK:       " + record.getTitle() + " (ISBN: " + record.getISBN() + ")");
        System.out.println("MEMBER:     " + record.getMemberName() + " [ID: " + record.getMemberId() + "]");
        System.out.println("-------------------------------------------");
        System.out.println("BORROWED:   " + record.getBorrowDate() + " to " + record.getReturnDate());
        System.out.println("STATUS:     " + record.getDaysLate() + " Days Late");
        System.out.println("-------------------------------------------");
        System.out.printf("FINE RATE:  FRW %.2f /day\n", record.getFineAmount());
        System.out.printf("TOTAL FINE: FRW %.2f\n", record.calculateFine());
        System.out.println("-------------------------------------------");
        System.out.println("PAID VIA:   " + record.getPaymentMode() + " on " + record.getPaymentDate());
        System.out.println("===========================================");
        System.out.println("Generated by ID: 27089");

        sc.close();
    }

    // --- HELPER METHODS ---

    private static void getString(String prompt, Consumer<String> setter) {
        while (true) {
            System.out.print(prompt);
            String input = sc.nextLine();
            try {
                setter.accept(input);
                break;
            } catch (RuntimeException e) {
                System.err.println("  [Error]: " + e.getMessage() + ". Try again.");
            }
        }
    }

    private static void getInt(String prompt, IntConsumer setter) {
        while (true) {
            System.out.print(prompt);
            try {
                int val = Integer.parseInt(sc.nextLine());
                setter.accept(val);
                break;
            } catch (NumberFormatException e) {
                System.err.println("  [Error]: Invalid number. Try again.");
            } catch (RuntimeException e) {
                System.err.println("  [Error]: " + e.getMessage() + ". Try again.");
            }
        }
    }

    private static void getDouble(String prompt, DoubleConsumer setter) {
        while (true) {
            System.out.print(prompt);
            try {
                double val = Double.parseDouble(sc.nextLine());
                setter.accept(val);
                break;
            } catch (NumberFormatException e) {
                System.err.println("  [Error]: Invalid decimal. Try again.");
            } catch (RuntimeException e) {
                System.err.println("  [Error]: " + e.getMessage() + ". Try again.");
            }
        }
    }
}